name: Build and Upload Artifact

# on:
#   push:
#     branches:
#       - main

jobs:
  build:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Setup Maven
        uses: stCarolas/setup-maven@v4
        with:
          maven-version: '3.9.9'

      - name: Build project
        run: mvn clean install -DskipTests

      - name: Upload Built Source
        uses: actions/upload-artifact@v4
        with:
          name: built-source
          path: .
