name: QA Automation Pipeline

on:
  workflow_dispatch:
    inputs:
      whichEnv:
        description: "Environment to Run QA Automation"
        required: true
        default: "sit"
        type: choice
        options:
          - sit
          - UAT
      testTag:
        description: "Cucumber Tag to Run"
        required: true
        default: "@Regression"
        type: choice
        options:
          - "@Regression"
          - "@Smoke"
          - "@Acceptance"

  schedule:
    - cron: "30 14 * * *" # Daily at 8:00 PM IST (2:30 PM UTC)

jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: Checkout QA Automation Repo
        uses: actions/checkout@v4

      - name: Set up Java 21
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 21

      - name: Echo Secrets
        run: |
          echo "Username: ${{ secrets.SVCUSERNAME }}"
          echo "Password: ${{ secrets.SVCPASSWORD }}"
          echo "TENANT_ID: ${{ secrets.AZURE_AD_TENANT_ID }}"
          echo "CLIENT_ID: ${{ secrets.AZURE_AD_CLIENT_ID }}"
          echo "CLIENT_SECRET: ${{ secrets.AZURE_AD_CLIENT_SECRET }}"
          echo "QaReportstorageAccountName: ${{ secrets.QA_REPORT_STORAGE_ACCOUNT_NAME }}"
          echo "QaReportstorageAccountKey: ${{ secrets.QA_REPORT_STORAGE_ACCOUNT_KEY }}"

  
