name: QA Automation Pipeline

on:
  workflow_dispatch:
    inputs:
      whichEnv:
        description: "Environment to Run QA Automation"
        required: true
        default: "sit"
        type: choice
        options: [sit, UAT]
      testTag:
        description: "Cucumber Tag to Run"
        required: true
        default: "@Regression"
        type: choice
        options: ["@Regression", "@Smoke", "@Acceptance"]

  schedule:
    - cron: "30 14 * * *" # Daily at 8:00 PM IST (2:30 PM UTC)
    
permissions:
  contents: read
  actions: write

jobs:
  install_build_tools:
    runs-on: windows-latest
    environment: ${{ github.event.inputs.whichEnv || 'sit' }}

    env:
      WHICH_ENV: ${{ github.event.inputs.whichEnv }}
      TEST_TAG: ${{ github.event.inputs.testTag }}
      MAVEN_RUN_ENV: ${{ github.event.inputs.whichEnv == 'sit' && 'ENPLSIT' || 'ENPLUAT' }}
      REPORT_SA_CONTAINER: ${{ github.event.inputs.whichEnv == 'sit' && 'sit-reports' || 'uat-reports' }}
      MAVEN_REPO_LOCAL: ${{ github.workspace }}/.m2/repository
      
    steps:
      - uses: actions/checkout@v4

      - name: Download Last Successful Built Source
        uses: dawidd6/action-download-artifact@v6
        with:
          workflow: Build and Upload Artifact
          workflow_conclusion: success
          name: built-source
          branch: main
          path: ./built